version: "3"
services:
  api1:
    build: ./api1
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
  api2:
    build: ./api2
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # RabbitMQ management port